---
sidebar: sidebar
permalink: concept-deploy-netapp-console-local.html
keywords: deploy, install, vCenter, Linux, high availability, deployment options, netapp console local
summary: "Learn about deployment options for NetApp Console (local), including vCenter and Linux installations."
---
= Deploy NetApp Console (local)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp Console (local) can be deployed in your on-premises environment using either a VMware vCenter appliance.

== Deployment options

Choose the deployment method that fits your environment.

=== Install in your vCenter environment

Deploy NetApp Console (local) as a virtual appliance in your VMware vCenter environment using a pre-configured OVA image.

link:task-install-agent-on-prem-ova.html[Install NetApp Console (local) in your vCenter environment]


== Next steps

After deployment, complete the following tasks to get started:

* link:task-storage-discover.html[Discover storage in NetApp Console (local)]
* link:task-iam-manage-members-permissions.html[Add members and assign roles in NetApp Console (local)]
