---
sidebar: sidebar
permalink: concept-deploy-netapp-console-local.html
keywords: deploy, install, vCenter, Linux, high availability, deployment options, netapp console local
summary: "Learn about deployment options for NetApp Console Local, including vCenter and Linux installations."
---
= Deploy NetApp Console Local
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp Console Local can be deployed in your on-premises environment using either a VMware vCenter appliance or a Linux host installation. After installation, you can optionally deploy a high-availability configuration for resilience.

== Deployment options

Choose the deployment method that fits your environment.

=== Install in your vCenter environment

Deploy NetApp Console Local as a virtual appliance in your VMware vCenter environment using a pre-configured OVA image.

link:task-install-agent-on-prem-ova.html[Install NetApp Console Local in your vCenter environment]


== Next steps

After deployment, complete the following tasks to get started:

* link:task-console-organization-verify.html[Verify your NetApp Console Local organization]
* link:task-storage-discover.html[Discover storage in NetApp Console Local]
* link:task-iam-manage-members-permissions.html[Add users to NetApp Console Local]
