---
sidebar: sidebar
permalink: reference-iam-storage-roles.html
keywords: predefined roles, iam roles, organization admin, folder or fleet admin, identity and access management, access roles, admin
summary: You can assign the following roles to users to provide them access to the storage management features in the NetApp Console. You can assign users an administrative role to manage storage or a viewer role for monitoring.
---

= Storage access roles for NetApp Console (local)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]

You can assign the following roles to users to provide them access to the storage management features in NetApp Console (local). You can assign users an administrative role to manage storage or a viewer role for monitoring.

NOTE: These roles are not available from the NetApp Console (local) partnership API.

Administrators can assign storage roles to users for the following storage resources and features:

Storage resources: 

* On-premises ONTAP clusters
* StorageGRID
* E-Series

Console services and features:

* Digital advisor
* Software updates
* Lifecycle planning
* Sustainability


.Example for storage roles in NetApp Console (local)

XYZ Corporation, a multinational company, has a large team of storage engineers and storage administrators. They allow this team to manage storage assets for their regions while limiting access to core Console (local) tasks like user management  and license management.
 
Within a team of 12, two users are given the *Storage viewer* role which allows them to monitor the storage resources associated with the Console (local) fleets they are assigned to. The remaining nine are given the *Storage admin* role which includes the ability to manage software updates, access ONTAP System Manager through the Console (local), as well as discover storage resources (add systems). One person on the team is given the *System health specialist* role so they can manage the health of the storage resources in their region, but not modify or delete any systems. This person can also perform software updates on the storage resources for fleets they are assigned.
 
The organization has two additional users with the *Organization admin* role who can manage all aspects of the Console (local), including user management and license management, as well as several users with the *Folder or fleet admin* role who can perform Console (local) administration tasks for the folders and fleets they are assigned to.


The following table shows the actions each storage role performs.

[cols=4*,options="header",cols="40,20a,20a,20a", width="100%"]
|===
| Feature and action
| Storage admin
| System health specialist
| Storage viewer


4+| *Storage Management*:
| Discover new resources (create systems) | Yes | Yes | No
| View discovered systems | Yes | Yes | No
| Delete systems from the Console| Yes | No | No
| Modify systems| Yes | No | No
4+| *System manager access*
| May enter credentials | Yes | Yes | No


|===

