---
sidebar: sidebar
permalink: reference-local-known-limitations.html
keywords: card templates, dashboard cards, metric types, chart types, performance, capacity, health, alerts, netapp console local
summary: "Reference for known limitations in NetApp Console local deployment."
---
= Known limitations in NetApp Console local deployment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.

These limitations are specific to the setup for the NetApp Console and administration: the agent, the software as a service (SaaS) platform, and more.

== Console VM limitations

=== Possible conflict with IP addresses in the <placeholder> range
Possible conflict with IP addresses in the 172 range
The NetApp Console local deployment VM deploys with two interfaces that have IP addresses in the 172.17.0.0/16 and 172.18.0.0/16 ranges.

If your network has a subnet configured with either of these ranges, then you might experience connectivity failures from the Console. For example, discovering on-premises ONTAP clusters in the Console might fail.

See Knowledge Base article Agent IP conflict with existing network for instructions on how to change the IP address of the agent’s interfaces.



=== Shared Linux hosts are not supported
The agent isn't supported on a VM that is shared with other applications. The VM must be dedicated to the agent software.

=== Third-party agents and extensions
Third-party agents or VM extensions are not supported on the agent VM.