---
sidebar: sidebar
permalink: task-storage-fleets-organize.html
keywords: organize, storage fleets, fleet, folder, group, storage systems, associate, netapp console
summary: "Organize discovered storage systems into folders and fleets for simplified management in NetApp Console (local)."
---
= Organize storage into fleets in NetApp Console (local)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
// Jira: SPSPM-3497

Use this page as an alternate entry point for resource-to-fleet organization. The canonical workflow is link:task-iam-manage-resources.html[Add resources to folders and fleets in NetApp Console], which includes viewing resources, associating resources, removing associations, and moving resources between fleets.

For full lifecycle guidance, use the canonical task.

* link:task-iam-manage-resources.html#associate-resource[Associate a resource with folders and fleets]
* link:task-iam-manage-resources.html#view-folders-and-fleets[View folders and fleets associated with a resource]
* link:task-iam-manage-resources.html#remove-resource[Remove a resource from a folder or fleet]
* link:task-iam-manage-resources.html[Move a resource between fleets]

Use the links above to complete the workflow from the canonical task page.
