---
sidebar: sidebar
permalink: task-get-help.html
keywords: help, ticket, open support case, support, netapp support, technical support, call support, phone number, open ticket, web ticket, open an issue
summary: NetApp provides support for NetApp Console local deployment in a variety of ways. Extensive free self-support options are available 24x7, such as knowledge base (KB) articles and a community forum. Your support registration includes remote technical support via web ticketing.
---

= Get help with NetApp Console local deployment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp provides support for NetApp Console local deployment in a variety of ways. Extensive free self-support options are available 24x7, such as knowledge base (KB) articles and a community forum. You can register for support with the serial number of any storage resource associated with NetApp Console local deployment, which includes remote technical support via web ticketing.

Open a support case with NetApp Console local deployment using one of the NetApp storage system serial numbers managed through your NetApp Console Local Deployment system.

.Steps

. Go to https://mysupport.netapp.com and log in with your NetApp Support credentials.
. Select *Cases and Parts > Create Technical Case".
. Enter the serial number of the NetApp Storage system that is associated with the Console local deployment product experiencing the issue.
. Create a new case and select the appropriate Category code for “NetApp Console local deployment”
