---
sidebar: sidebar
permalink: task-provisioning-manual.html
keywords: provisioning, provision storage, create volume, netapp console
summary: "Provision storage resources using NetApp Console local deployment."
---
= Provision storage in NetApp Console local deployment
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Provision volumes and LUNs in NetApp Console local deployment to make storage resources available for your workloads. During provisioning, you can optionally select a storage class to apply predefined storage policies and organizational standards.

.Required access roles
Super admin, Organization admin, Folder or fleet admin, or Storage admin. link:reference-iam-predefined-roles.html[Learn about access roles].

== Provision a volume

.Steps

. Select *Storage > Management*.

. Select *Fleets*.

. Select the fleet you want to provision into.

. Select *Add*.

. From the menu, select *Volume*.

. Under *Volume details*:
.. Enter a volume name.
.. Enter capacity (and choose units if needed).
.. (Optional) Select a storage class to apply storage class policies. If you don't select one, the volume is provisioned without storage class policies.

. Under *System details*:
.. Select a system from the eligible systems for the selected fleet.
.. Select a storage VM.

. Under *Host (NAS) details*, choose how hosts access the volume:
.. Export by NFS (export policies control which NFS hosts can access the volume)
.. Share by SMB/CIFS

. Select *Add*.

== Provision a LUN

.Steps

. Select *Storage > Management*.

. Select *Fleets*.

. Select the fleet you want to provision into.

. Select *Add*.

. From the menu, select *LUNs*.

. Under *LUN storage details*:
.. Enter a prefix name.
.. Enter the number of LUNs to create with that prefix.
.. Enter the capacity per LUN (and choose units if needed).
.. (Optional) Select a storage class to apply storage class policies. If you don't select one, the LUNs are provisioned without storage class policies.

. Under *System details*:
.. Select a system (if prompted).
.. Select a storage VM.

. Under *Host (SAN) details*, choose how hosts access the volume:
.. Choose the host operation system (for example, Windows or Linux) to set recommended defaults for LUN alignment and block size.
.. Choose the host mapping group to control which initiators can access the LUNs.

. Select *Add*.
