---
sidebar: sidebar
permalink: task-iam-manage-members-permissions.html
keywords: user, service account, member, role, permissions, organization, fleet, folder, iam, identity and access management, federated groups, SSO, access roles, add members, grant permissions
summary: Manage your organization's members to provide permissions across different levels of your organization's resource hierarchy.
---

= Add users to a NetApp Console organization
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Within the Console, you grant users access to fleets or folders to according to an access role. A _access role_ contains a set of permissions that enables a member (user or service account) to perform specific actions at the assigned level of the resource hierarchy. 

.Required access roles
Super admin, Org admin, or Folder or fleet admin (for folders and fleets that they are administering). link:reference-iam-predefined-roles.html[Learn about access roles].

== Understand how access is granted in NetApp Console           
NetApp Console uses role-based access control (RBAC) to manage permissions. Assign roles to users individually to provide them with the necessary permissions. Each role defines allowed actions for specific resources.

Note the following about granting access in NetApp Console:

* All users must first sign up for the NetApp Console before they can be granted access to resources, even if they are part of a federated group.
* You must explicitly assign a role to each user in the Console before they can access resources, even if they are members of a federated group that has been assigned a role.   
* You can add service accounts directly from the Console and assign them roles.



[#add-members]
== Add members to your organization

NetApp Console supports three types of members: user accounts, service accounts, and federated groups. 

Users must sign up for NetApp Console before you can add them and assign a role, even if they are in a federated group. Create service accounts directly in the Console.

All members must have at least one role explicitly assigned to them in order to access resources.

When adding a member, choose the resource level (organization, folder, or fleet) and assign a role or roles with the needed permissions.



=== Add a user

Users sign up for the NetApp Console, but an Org admin or Folder or fleet admin must add them to an organization, folder, or fleet so they can access resources.




.Steps

. Select *Administration > Identity and access*.

. Select *Members*.

. Select *Add a member*.

. For *Member Type*, keep *User* selected.
. For *User's email*, enter the user's email address that is associated with the login that they created.
. Use the *Select an organization, folder, or fleet* section to choose the level of your resource hierarchy that the member should have permissions for.

+ 
Note the following:

** You can select only the folders and fleets for which you have permissions.
** When you select an organization or folder, you grant the member permissions to all its contents.
** You can only assign the *Organization admin* role at the organization level.

. *Select a category* then select a *Role* that provides the member with permissions for the resources that are associated with the organization, folder, or fleet that you selected.

+
link:reference-iam-predefined-roles.html[Learn about access roles].

. To give access to more folders, fleets, or roles, select *Add role*, choose the folder, fleet, or role category, and select a role.

. Select *Add*. 
+
The Console emails instructions to the user.



[[service-account]]
=== Add a service account 
Service accounts allow you to automate tasks and securely connect with Console APIs. You'll need a client ID and secret for the account before adding it.


.Steps

. Select *Administration > Identity and access*.

. Select *Members*.

. Select *Add a member*.

. For *Member Type*, select *Service account*.

. Enter a name for the service account.


. Use the *Select an organization, folder, or fleet* section to choose the level of your resource hierarchy that the member should have permissions for.
+
Note the following:
+
** You can only select from the folders and fleets for which you have permissions.
** Selecting an organization or folder grants the member permissions to all its contents.
** You can only assign the *Organization admin* role at the organization level.

. Select a *Category* then select a *Role* that gives the member permissions for the resources in the organization, folder, or fleet you selected.

+
link:reference-iam-predefined-roles.html[Learn about access roles].

. To give access to more folders, fleets, or roles, select *Add role*, choose the folder, fleet, or role category, and select a role.

. Download or copy the client ID and client secret. 
+
The Console shows the client secret only once. Copy it securely; you can recreate it later if you lose it.


. Select *Close*.

== Add a directory user to your organization

You can add a directory user and assign them a role or roles. 

You must have first configured Directory service before you can add directory users. link:task-active-directory-integrate.html[Learn how to integrate with your directory service].



.Steps
. Select *Administration > Identity and access*.
. Select *Members*.
. Select *Add a member*.
. For *Member Type*, select *Directory user*.               
. For *User's email*, enter the email address of the directory user that you want to add. This email address must match the email address associated with the user's login in your directory.
. Use the *Select an organization, folder, or fleet* section to choose the level of your resource hierarchy that the member should have permissions for.
+
Note the following:
+
** You can only select from the folders and fleets for which you have permissions.
** Selecting an organization or folder grants the member permissions to all its contents.
** You can only assign the *Organization admin* role at the organization level.

. Select a *Category* then select a *Role* that gives the member permissions for the resources in the organization, folder, or fleet you selected.

+
link:reference-iam-predefined-roles.html[Learn about access roles].

. To give the user additional access access to other folders, fleets, or roles, select *Add role*, choose the folder or fleet, role category, and select a role.








== Related information

* link:concept-identity-and-access-management.html[Learn about identity and access management in NetApp Console]
* link:task-iam-get-started.html[Get started with identity and access]
* link:reference-iam-predefined-roles.html[NetApp Console access roles]
* https://docs.netapp.com/us-en/console-automation/tenancyv4/overview.html[Learn about the API for identity and access^]