---
permalink: performance-checker/legacy/task_use_workload_analyzer.html
sidebar: sidebar
keywords: workload analyzer, legacy
summary: "Legacy reference for launching the Active IQ Unified Manager workload analyzer from the UI."
---
= Legacy: Use the workload analyzer in Active IQ Unified Manager
:icons: font
:imagesdir: ../../media/

[.lead]
This legacy page is preserved for reference for the older Active IQ Unified Manager workload analyzer workflow.

There are many ways to start the workload analyzer from the user interface. Here we describe launching the tool from the left-navigation pane.

.Steps
. In the left navigation pane, click *Workload Analysis*.
+
The Workload Analysis page is displayed.

. If you know the workload name, enter the name. If you are not sure of the full name, enter a minimum of 3 characters and the system displays a list of workloads that match the string.
. Select the time range if you want to view statistics for longer than the default 2 hours and click *Apply*.
. View the Summary area to see the events that have occurred during the timeframe.
. View the performance and capacity charts to see when any of the metrics are abnormal and see if any events align with the abnormal entry.
// 2025-6-11, OTHERDOC-133